version: "2.3"
services:
    php:
        build: php
        volumes:
            - ./../:/code
        working_dir: /code
        command: php -S 0.0.0.0:80 -t public
        ports:
            - "8080:80"
        links:
            - db
        environment:
            APP_ENV: local
            APP_DEBUG: 'true'
            APP_KEY: SomeRandomKey!!!
            APP_LOCALE: en
            APP_FALLBACK_LOCALE: en
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_DATABASE: lumen
            DB_USERNAME: lumen
            DB_PASSWORD: secret
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: lumen
            MYSQL_USER: lumen
            MYSQL_PASSWORD: secret
    swagger:
        image: swaggerapi/swagger-editor